run-ui:
	python -m venv venv
	venv\Scripts\activate
	pip install -r requirements.txt
	python analyzer_ui.py
	
install:
	python -m venv venv
	venv\Scripts\activate
	pip install -r requirements.txt

clean:
	venv\Scripts\deactivate
	rm -rf venv
	rm -rf __pycache__

